# Generated by Django 5.1.3 on 2025-04-25 12:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citydb', '0007_alter_refurbishmentmeasure_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRIAssessor',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('organisation', models.CharField(blank=True, max_length=1000, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_assessor',
            },
        ),
        migrations.CreateModel(
            name='SRIAssetData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('assettype', models.CharField(blank=True, choices=[('buildingCharacteristics', 'Building Characteristics'), ('systemCharacteristics', 'System Characteristics'), ('other', 'Other')], max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_assetdata',
            },
        ),
        migrations.CreateModel(
            name='SRIBuilding',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.building')),
                ('buildingstate', models.CharField(blank=True, choices=[('Original', 'Original'), ('NormalRefurbishment', 'Normal Refurbishment'), ('AdvancedRefurbishment', 'Advanced Refurbishment'), ('Other', 'Other')], max_length=1000, null=True)),
                ('buildingusage', models.CharField(blank=True, choices=[('NonResidentialEducational', 'Non-Residential Educational'), ('NonResidentialHealthcare', 'Non-Residential Healthcare'), ('NonResidentialOffice', 'Non-Residential Office'), ('ResidentialLargeMultiFamilyHouse', 'Residential Large Multi-Family House'), ('ResidentialSmallMultiFamilyHouse', 'Residential Small Multi-Family House'), ('ResidentialSingleFamilyHouse', 'Residential Single-Family House'), ('ResidentialOther', 'Residential Other'), ('Other', 'Other')], max_length=1000, null=True)),
                ('climatezone', models.CharField(blank=True, choices=[('NorthEastEurope', 'North East Europe'), ('NorthEurope', 'North Europe'), ('WestEurope', 'West Europe'), ('SouthEastEurope', 'South East Europe'), ('SouthEurope', 'South Europe'), ('Other', 'Other')], max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('sribuildingtype', models.CharField(blank=True, choices=[('Residential', 'Residential'), ('NonResidential', 'Non-Residential'), ('Other', 'Other')], max_length=1000, null=True)),
                ('usefulfloorarea', models.CharField(blank=True, max_length=1000, null=True)),
                ('sridescription', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_building',
            },
        ),
        migrations.CreateModel(
            name='SRIDatacategoryMeta',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('datascale', models.CharField(blank=True, choices=[('room', 'Room'), ('building', 'Building'), ('district', 'District'), ('system', 'System'), ('floor', 'Floor'), ('otherSpatialScale', 'Other Spatial Scale'), ('equipment', 'Equipment'), ('zone', 'Zone'), ('circuit', 'Circuit')], max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_datacategorymeta',
            },
        ),
        migrations.CreateModel(
            name='SRICyberDeviceData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('cyberdevicetype', models.CharField(blank=True, choices=[('proxy', 'Proxy'), ('cyberAttack', 'Cyber Attack'), ('other', 'Other')], max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_cyberdevicedata',
            },
        ),
        migrations.CreateModel(
            name='SRIDataConnector',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('modelschema', models.CharField(blank=True, max_length=1000, null=True)),
                ('urlmodelschema', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sri_dataconnector',
            },
        ),
        migrations.CreateModel(
            name='SRIDataSource',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('objectclass', models.ForeignKey(db_column='objectclass_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='citydb.objectclass')),
            ],
            options={
                'db_table': 'sri_datasource',
            },
        ),
        migrations.CreateModel(
            name='SRIIndoorEnvironmentalData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('environmentaldatatype', models.CharField(blank=True, choices=[('thermal', 'Thermal'), ('visual', 'Visual'), ('airQuality', 'Air Quality'), ('acoustic', 'Acoustic'), ('noise', 'Noise'), ('solar', 'Solar'), ('other', 'Other'), ('wind', 'Wind')], max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_indoorenvironmentalda',
            },
        ),
        migrations.CreateModel(
            name='SRIMethodology',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('preferredservicecatalogue', models.CharField(blank=True, max_length=1000, null=True)),
                ('preferredweightings', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_methodology',
            },
        ),
        migrations.CreateModel(
            name='SRIOnsiteenergygeneration',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('nonrenewableenergy', models.CharField(blank=True, choices=[('onSiteConventionalEnergy', 'On-site Conventional Energy'), ('otherNonRenewableEnergy', 'Other Non-Renewable Energy')], max_length=1000, null=True)),
                ('renewableenergy', models.CharField(blank=True, choices=[('solarEnergy', 'Solar Energy'), ('windEnergy', 'Wind Energy'), ('thermalEnergy', 'Thermal Energy'), ('otherRenewableEnergy', 'Other Renewable Energy')], max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_onsiteenergygeneratio',
            },
        ),
        migrations.CreateModel(
            name='SRIOutdoorenvironmentalData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('environmentaldatatype', models.CharField(blank=True, choices=[('thermal', 'Thermal'), ('visual', 'Visual'), ('airQuality', 'Air Quality'), ('acoustic', 'Acoustic'), ('noise', 'Noise'), ('solar', 'Solar'), ('other', 'Other'), ('wind', 'Wind')], max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_outdoorenvironmentald',
            },
        ),
        migrations.CreateModel(
            name='SRIServiceCatalogue',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.building')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('version', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='Version must be greater than 0')])),
            ],
            options={
                'db_table': 'sri_servicecatalogue',
            },
        ),
        migrations.CreateModel(
            name='SRISupportedAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('hasapi', models.IntegerField(blank=True, db_column='hasapi', null=True)),
                ('hasendpoint', models.IntegerField(blank=True, db_column='hasendpoint', null=True)),
            ],
            options={
                'db_table': 'sri_supportedaccess',
            },
        ),
        migrations.CreateModel(
            name='SRIUsecase',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_usecase',
            },
        ),
        migrations.CreateModel(
            name='SRIControlLogic',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatacategorymeta')),
                ('controlsystem', models.CharField(blank=True, choices=[('hvac', 'HVAC'), ('lighting', 'Lighting'), ('fenestration', 'Fenestration'), ('plant', 'Plant'), ('other', 'Other')], max_length=1000, null=True)),
                ('controltype', models.CharField(blank=True, choices=[('logic', 'Logic'), ('setpoint', 'Setpoint'), ('schedule', 'Schedule'), ('other', 'Other')], max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_controllogic',
            },
        ),
        migrations.CreateModel(
            name='SRIEnergyData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatacategorymeta')),
                ('enduse', models.CharField(blank=True, choices=[('hvac', 'HVAC'), ('lighting', 'Lighting'), ('appliances', 'Appliances'), ('DHW', 'DHW'), ('Pump', 'Pumps'), ('ventilation', 'Ventilation'), ('other', 'Other')], max_length=1000, null=True)),
                ('energysource', models.CharField(blank=True, choices=[('fuel', 'Fuel'), ('electricity', 'Electricity'), ('other', 'Other')], max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_energydata',
            },
        ),
        migrations.CreateModel(
            name='SRIOperationalData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatacategorymeta')),
                ('systemdata', models.CharField(blank=True, choices=[('hvac', 'HVAC'), ('lighting', 'Lighting'), ('fenestration', 'Fenestration'), ('plant', 'Plant'), ('hotWater', 'Hot Water'), ('nonHeatedWater', 'Non Heated Water'), ('equipment', 'Equipment'), ('energyStorage', 'Energy Storage'), ('other', 'Other')], max_length=1000, null=True)),
                ('systemtype', models.CharField(blank=True, choices=[('log', 'Log'), ('fault', 'Fault'), ('other', 'Other')], max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_operationaldata',
            },
        ),
        migrations.CreateModel(
            name='SRIInterface',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatasource')),
                ('supportedaccesst_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('supportedaccesst_hasendpoint', models.IntegerField(blank=True, null=True)),
                ('supportedaccesstype_hasapi', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sri_interface',
            },
        ),
        migrations.CreateModel(
            name='SRIModel',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatasource')),
            ],
            options={
                'db_table': 'sri_model',
            },
        ),
        migrations.CreateModel(
            name='SRIInformationNeed',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('objectclass', models.ForeignKey(db_column='objectclass_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='citydb.objectclass')),
            ],
            options={
                'db_table': 'sri_informationneed',
            },
        ),
        migrations.CreateModel(
            name='SRISriAssessment',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('dateofassessment', models.DateTimeField(blank=True, null=True)),
                ('methodology', models.CharField(blank=True, max_length=1000, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('assessor_id', models.ForeignKey(blank=True, db_column='assessor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='sridb.sriassessor')),
            ],
            options={
                'db_table': 'sri_sriassessment',
            },
        ),
        migrations.CreateModel(
            name='SRISriservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=1000, null=True)),
                ('servicename', models.CharField(blank=True, max_length=1000, null=True)),
                ('descriptionfunctionalityleve', models.CharField(blank=True, max_length=1000, null=True)),
                ('functionalitylevel', models.IntegerField(blank=True, choices=[('Functionality level 0', 'Functionality level 0 (as non-smart default)'), ('functionalityLevel1', 'Functionality level 1'), ('functionalityLevel2', 'Functionality level 2'), ('functionalityLevel3', 'Functionality level 3'), ('functionalityLevel4', 'Functionality level 4')], null=True)),
                ('impact', models.CharField(blank=True, max_length=1000, null=True)),
                ('_partofmethoda', models.IntegerField(blank=True, db_column='partofmethoda', null=True)),
                ('_partofmethodb', models.IntegerField(blank=True, db_column='partofmethodb', null=True)),
                ('preconditions', models.CharField(blank=True, max_length=1000, null=True)),
                ('servicegroup', models.CharField(blank=True, max_length=1000, null=True)),
                ('sharefunctionalitylevel', models.IntegerField(blank=True, null=True)),
                ('sridomain', models.CharField(blank=True, choices=[('dynamicBuildingEnvelope', 'Dynamic Building Envelope'), ('heating', 'Heating'), ('electricVehicleCharging', 'Electric Vehicle Charging'), ('cooling', 'Cooling'), ('lighting', 'Lighting'), ('monitoringAndControl', 'Monitoring and Control'), ('ventilation', 'Ventilation'), ('domesticHotWater', 'Domestic Hot Water'), ('electricity', 'Electricity'), ('other', 'Other')], max_length=1000, null=True)),
                ('_userdefined', models.IntegerField(blank=True, db_column='userdefined', null=True)),
                ('assessment', models.ForeignKey(blank=True, db_column='sriassessment_sriservice_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='sridb.srisriassessment')),
                ('building', models.ForeignKey(blank=True, db_column='building_sriservice_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='sridb.sribuilding')),
                ('catalogue', models.ForeignKey(blank=True, db_column='servicecatalog_sriservice_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sri_services', to='sridb.sriservicecatalogue')),
            ],
            options={
                'db_table': 'sri_sriservice',
            },
        ),
        migrations.CreateModel(
            name='SRIDevice',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatasource')),
                ('manufacturer', models.CharField(blank=True, max_length=1000, null=True)),
                ('supportedaccesst_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('supportedaccesst_hasendpoint', models.IntegerField(blank=True, null=True)),
                ('supportedaccesstype_hasapi', models.IntegerField(blank=True, null=True)),
                ('supportedprotcolls', models.TextField(blank=True, null=True)),
                ('objectclass', models.ForeignKey(db_column='objectclass_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='citydb.objectclass')),
            ],
            options={
                'db_table': 'sri_device',
            },
        ),
        migrations.AddIndex(
            model_name='sridatasource',
            index=models.Index(fields=['objectclass'], name='sri_datasou_objectc_d89058_idx'),
        ),
        migrations.AddIndex(
            model_name='sriinformationneed',
            index=models.Index(fields=['objectclass'], name='sri_informa_objectc_2b43d0_idx'),
        ),
        migrations.AddIndex(
            model_name='srisriassessment',
            index=models.Index(fields=['assessor_id'], name='sri_sriasse_assesso_98b96a_idx'),
        ),
        migrations.AddIndex(
            model_name='srisriservice',
            index=models.Index(fields=['catalogue'], name='sri_sriserv_service_b1a689_idx'),
        ),
        migrations.AddIndex(
            model_name='srisriservice',
            index=models.Index(fields=['building'], name='sri_sriserv_buildin_abb59d_idx'),
        ),
        migrations.AddIndex(
            model_name='sridevice',
            index=models.Index(fields=['objectclass'], name='sri_device_objectc_7ea93d_idx'),
        ),
    ]
