# Generated by Django 5.1.3 on 2025-04-21 19:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citydb', '0006_alter_abstractconstruction_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRIAssessor',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('organisation', models.CharField(blank=True, max_length=1000, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_assessor',
            },
        ),
        migrations.CreateModel(
            name='SRIAssetData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('assettype', models.CharField(blank=True, choices=[('buildingCharacteristics', 'Building Characteristics'), ('systemCharacteristics', 'System Characteristics'), ('other', 'Other')], max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_assetdata',
            },
        ),
        migrations.CreateModel(
            name='SRIBuilding',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.building')),
                ('buildingstate', models.CharField(blank=True, choices=[('Original', 'Original'), ('NormalRefurbishment', 'Normal Refurbishment'), ('AdvancedRefurbishment', 'Advanced Refurbishment'), ('Other', 'Other')], max_length=1000, null=True)),
                ('buildingusage', models.CharField(blank=True, choices=[('NonResidentialEducational', 'Non-Residential Educational'), ('NonResidentialHealthcare', 'Non-Residential Healthcare'), ('NonResidentialOffice', 'Non-Residential Office'), ('ResidentialLargeMultiFamilyHouse', 'Residential Large Multi-Family House'), ('ResidentialSmallMultiFamilyHouse', 'Residential Small Multi-Family House'), ('ResidentialSingleFamilyHouse', 'Residential Single-Family House'), ('ResidentialOther', 'Residential Other'), ('Other', 'Other')], max_length=1000, null=True)),
                ('climatezone', models.CharField(blank=True, choices=[('NorthEastEurope', 'North East Europe'), ('NorthEurope', 'North Europe'), ('WestEurope', 'West Europe'), ('SouthEastEurope', 'South East Europe'), ('SouthEurope', 'South Europe'), ('Other', 'Other')], max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('sribuildingtype', models.CharField(blank=True, choices=[('Residential', 'Residential'), ('NonResidential', 'Non-Residential'), ('Other', 'Other')], max_length=1000, null=True)),
                ('usefulfloorarea', models.CharField(blank=True, max_length=1000, null=True)),
                ('sridescription', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_building',
            },
        ),
        migrations.CreateModel(
            name='SRIDatacategoryMeta',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('datascale', models.CharField(blank=True, choices=[('room', 'Room'), ('building', 'Building'), ('district', 'District'), ('system', 'System'), ('floor', 'Floor'), ('otherSpatialScale', 'Other Spatial Scale'), ('equipment', 'Equipment'), ('zone', 'Zone'), ('circuit', 'Circuit')], max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_datacategorymeta',
            },
        ),
        migrations.CreateModel(
            name='SRICyberDeviceData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('cyberdevicetype', models.CharField(blank=True, choices=[('proxy', 'Proxy'), ('cyberAttack', 'Cyber Attack'), ('other', 'Other')], max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_cyberdevicedata',
            },
        ),
        migrations.CreateModel(
            name='SRIDataConnector',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('modelschema', models.CharField(blank=True, max_length=1000, null=True)),
                ('urlmodelschema', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SRI_dataconnector',
            },
        ),
        migrations.CreateModel(
            name='SRIDataSource',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('objectclass', models.ForeignKey(db_column='objectclass_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='citydb.objectclass')),
            ],
            options={
                'db_table': 'SRI_datasource',
            },
        ),
        migrations.CreateModel(
            name='SRIDomain',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('category', models.CharField(blank=True, choices=[('dynamicBuildingEnvelope', 'Dynamic Building Envelope'), ('heating', 'Heating'), ('electricVehicleCharging', 'Electric Vehicle Charging'), ('cooling', 'Cooling'), ('lighting', 'Lighting'), ('monitoringAndControl', 'Monitoring and Control'), ('ventilation', 'Ventilation'), ('domesticHotWater', 'Domestic Hot Water'), ('electricity', 'Electricity')], max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_domain',
            },
        ),
        migrations.CreateModel(
            name='SRIIndoorEnvironmentalData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('environmentaldatatype', models.CharField(blank=True, choices=[('thermal', 'Thermal'), ('visual', 'Visual'), ('airQuality', 'Air Quality'), ('acoustic', 'Acoustic'), ('noise', 'Noise'), ('solar', 'Solar'), ('other', 'Other'), ('wind', 'Wind')], max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_indoorenvironmentaldata',
            },
        ),
        migrations.CreateModel(
            name='SRIMethodology',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('preferredservicecatalogue', models.CharField(blank=True, max_length=1000, null=True)),
                ('preferredweightings', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_methodology',
            },
        ),
        migrations.CreateModel(
            name='SRIOnsiteenergygeneration',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('nonrenewableenergy', models.CharField(blank=True, choices=[('onSiteConventionalEnergy', 'On-site Conventional Energy'), ('otherNonRenewableEnergy', 'Other Non-Renewable Energy')], max_length=1000, null=True)),
                ('renewableenergy', models.CharField(blank=True, choices=[('solarEnergy', 'Solar Energy'), ('windEnergy', 'Wind Energy'), ('thermalEnergy', 'Thermal Energy'), ('otherRenewableEnergy', 'Other Renewable Energy')], max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_onsiteenergygeneration',
            },
        ),
        migrations.CreateModel(
            name='SRIOutdoorenvironmentalData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('environmentaldatatype', models.CharField(blank=True, choices=[('thermal', 'Thermal'), ('visual', 'Visual'), ('airQuality', 'Air Quality'), ('acoustic', 'Acoustic'), ('noise', 'Noise'), ('solar', 'Solar'), ('other', 'Other'), ('wind', 'Wind')], max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_outdoorenvironmentaldata',
            },
        ),
        migrations.CreateModel(
            name='SRIServiceCatalogue',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('version', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='Version must be greater than 0')])),
            ],
            options={
                'db_table': 'sri_service_catalogue',
            },
        ),
        migrations.CreateModel(
            name='SRISupportedAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('hasapi', models.IntegerField(blank=True, db_column='hasapi', null=True)),
                ('hasendpoint', models.IntegerField(blank=True, db_column='hasendpoint', null=True)),
            ],
            options={
                'db_table': 'SRI_supportedaccess',
            },
        ),
        migrations.CreateModel(
            name='SRIUsecase',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_usecase',
            },
        ),
        migrations.CreateModel(
            name='SRIBuildingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citydb.building')),
            ],
            options={
                'db_table': 'sri_building_assessment',
            },
        ),
        migrations.CreateModel(
            name='SRIControlLogic',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatacategorymeta')),
                ('controlsystem', models.CharField(blank=True, choices=[('hvac', 'HVAC'), ('lighting', 'Lighting'), ('fenestration', 'Fenestration'), ('plant', 'Plant'), ('other', 'Other')], max_length=1000, null=True)),
                ('controltype', models.CharField(blank=True, choices=[('logic', 'Logic'), ('setpoint', 'Setpoint'), ('schedule', 'Schedule'), ('other', 'Other')], max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_controllogic',
            },
        ),
        migrations.CreateModel(
            name='SRIEnergyData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatacategorymeta')),
                ('enduse', models.CharField(blank=True, choices=[('hvac', 'HVAC'), ('lighting', 'Lighting'), ('appliances', 'Appliances'), ('DHW', 'DHW'), ('Pump', 'Pumps'), ('ventilation', 'Ventilation'), ('other', 'Other')], max_length=1000, null=True)),
                ('energysource', models.CharField(blank=True, choices=[('fuel', 'Fuel'), ('electricity', 'Electricity'), ('other', 'Other')], max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_energydata',
            },
        ),
        migrations.CreateModel(
            name='SRIOperationalData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatacategorymeta')),
                ('systemdata', models.CharField(blank=True, choices=[('hvac', 'HVAC'), ('lighting', 'Lighting'), ('fenestration', 'Fenestration'), ('plant', 'Plant'), ('hotWater', 'Hot Water'), ('nonHeatedWater', 'Non Heated Water'), ('equipment', 'Equipment'), ('energyStorage', 'Energy Storage'), ('other', 'Other')], max_length=1000, null=True)),
                ('systemtype', models.CharField(blank=True, choices=[('log', 'Log'), ('fault', 'Fault'), ('other', 'Other')], max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sri_operationaldata',
            },
        ),
        migrations.CreateModel(
            name='SRIInterface',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatasource')),
                ('supportedaccesst_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('supportedaccesst_hasendpoint', models.IntegerField(blank=True, null=True)),
                ('supportedaccesstype_hasapi', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SRI_interface',
            },
        ),
        migrations.CreateModel(
            name='SRIModel',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatasource')),
            ],
            options={
                'db_table': 'SRI_model',
            },
        ),
        migrations.CreateModel(
            name='SRIInformationNeed',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('objectclass', models.ForeignKey(db_column='objectclass_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='citydb.objectclass')),
            ],
            options={
                'db_table': 'SRI_informationneed',
            },
        ),
        migrations.CreateModel(
            name='SRISriAssessment',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('dateofassessment', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('assessor_assessments', models.ForeignKey(blank=True, db_column='assessor_assessments_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sri_assessments', to='sridb.sriassessor')),
                ('buildings', models.ManyToManyField(blank=True, related_name='assessments', through='sridb.SRIBuildingAssessment', to='citydb.building')),
                ('methodology_assessments', models.ForeignKey(blank=True, db_column='methodology_assessments_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sri_assessments', to='sridb.srimethodology')),
                ('sri_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sri_assessments', to='sridb.sribuilding')),
            ],
            options={
                'db_table': 'sri_sriassessment',
            },
        ),
        migrations.AddField(
            model_name='sribuildingassessment',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sridb.srisriassessment'),
        ),
        migrations.CreateModel(
            name='SRIAssessmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sridb.srisriassessment')),
            ],
            options={
                'db_table': 'sri_assessment_service',
            },
        ),
        migrations.CreateModel(
            name='SRISriservice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=1000, null=True)),
                ('domain', models.CharField(blank=True, max_length=1000, null=True)),
                ('impact', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('partofmethod', models.IntegerField(blank=True, null=True)),
                ('partofmethodb', models.IntegerField(blank=True, null=True)),
                ('preconditions', models.CharField(blank=True, max_length=1000, null=True)),
                ('servicegroup', models.CharField(blank=True, max_length=1000, null=True)),
                ('userdefined', models.IntegerField(blank=True, null=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sri_services', to='sridb.sriservicecatalogue')),
            ],
            options={
                'db_table': 'sri_sriservice',
            },
        ),
        migrations.AddField(
            model_name='srisriassessment',
            name='sri_services',
            field=models.ManyToManyField(blank=True, related_name='sri_assessments', through='sridb.SRIAssessmentService', to='sridb.srisriservice'),
        ),
        migrations.CreateModel(
            name='SRIFunctionalitylevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('functionalitylevel', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('sri_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functionality_levels', to='sridb.srisriservice')),
            ],
            options={
                'db_table': 'sri_functionalitylevel',
            },
        ),
        migrations.AddField(
            model_name='sriassessmentservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sridb.srisriservice'),
        ),
        migrations.CreateModel(
            name='SRIDevice',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatasource')),
                ('manufacturer', models.CharField(blank=True, max_length=1000, null=True)),
                ('supportedaccesst_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('supportedaccesst_hasendpoint', models.IntegerField(blank=True, null=True)),
                ('supportedaccesstype_hasapi', models.IntegerField(blank=True, null=True)),
                ('supportedprotcolls', models.TextField(blank=True, null=True)),
                ('objectclass', models.ForeignKey(db_column='objectclass_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='citydb.objectclass')),
            ],
            options={
                'db_table': 'SRI_device',
            },
        ),
        migrations.AddIndex(
            model_name='sridatasource',
            index=models.Index(fields=['objectclass'], name='SRI_datasou_objectc_f00fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='sriinformationneed',
            index=models.Index(fields=['objectclass'], name='SRI_informa_objectc_caa397_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sribuildingassessment',
            unique_together={('building', 'assessment')},
        ),
        migrations.AddIndex(
            model_name='srisriservice',
            index=models.Index(fields=['catalogue'], name='sri_sriserv_catalog_8bfdcc_idx'),
        ),
        migrations.AddIndex(
            model_name='srisriassessment',
            index=models.Index(fields=['sri_building'], name='sri_sriasse_sri_bui_a225c2_idx'),
        ),
        migrations.AddIndex(
            model_name='srisriassessment',
            index=models.Index(fields=['assessor_assessments'], name='sri_sriasse_assesso_0390a9_idx'),
        ),
        migrations.AddIndex(
            model_name='srisriassessment',
            index=models.Index(fields=['methodology_assessments'], name='sri_sriasse_methodo_e2df34_idx'),
        ),
        migrations.AddIndex(
            model_name='srifunctionalitylevel',
            index=models.Index(fields=['sri_service'], name='sri_functio_sri_ser_9ec021_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sriassessmentservice',
            unique_together={('assessment', 'service')},
        ),
        migrations.AddIndex(
            model_name='sridevice',
            index=models.Index(fields=['objectclass'], name='SRI_device_objectc_a8de5e_idx'),
        ),
    ]
