# Generated by Django 5.1.3 on 2025-04-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citydb', '0006_alter_abstractconstruction_table_and_more'),
        ('sridb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRIAssetData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('assettype', models.CharField(blank=True, choices=[('buildingCharacteristics', 'Building Characteristics'), ('systemCharacteristics', 'System Characteristics'), ('other', 'Other')], max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'SRI_assetdata',
            },
        ),
        migrations.CreateModel(
            name='SRIDatacategoryMeta',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('datascale', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('designtype', models.CharField(blank=True, max_length=1000, null=True)),
                ('occupanttype', models.CharField(blank=True, max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
                ('utilitygridtype', models.CharField(blank=True, max_length=1000, null=True)),
                ('objectclass', models.ForeignKey(db_column='objectclass_id', on_delete=django.db.models.deletion.CASCADE, to='citydb.objectclass')),
            ],
            options={
                'db_table': 'SRI_datacategorymeta',
            },
        ),
        migrations.CreateModel(
            name='SRICyberDeviceData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('cyberdevicetype', models.CharField(blank=True, choices=[('proxy', 'Proxy'), ('cyberAttack', 'Cyber Attack'), ('other', 'Other')], max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'SRI_cyberdevicedata',
            },
        ),
        migrations.CreateModel(
            name='SRIIndoorEnvironmentalData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('environmentaldatatype', models.CharField(blank=True, choices=[('thermal', 'Thermal'), ('visual', 'Visual'), ('airQuality', 'Air Quality'), ('acoustic', 'Acoustic'), ('noise', 'Noise'), ('solar', 'Solar'), ('other', 'Other'), ('wind', 'Wind')], max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'SRI_indoorenvironmentalda',
            },
        ),
        migrations.CreateModel(
            name='SRIOnsiteenergygeneratio',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('nonrenewableenergy', models.CharField(blank=True, choices=[('onSiteConventionalEnergy', 'On-site Conventional Energy'), ('otherNonRenewableEnergy', 'Other Non-Renewable Energy')], max_length=1000, null=True)),
                ('renewableenergy', models.CharField(blank=True, choices=[('solarEnergy', 'Solar Energy'), ('windEnergy', 'Wind Energy'), ('thermalEnergy', 'Thermal Energy'), ('otherRenewableEnergy', 'Other Renewable Energy')], max_length=1000, null=True)),
            ],
            options={
                'db_table': 'SRI_onsiteenergygeneratio',
            },
        ),
        migrations.CreateModel(
            name='SRIOutdoorenvironmentalData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citydb.cityobject')),
                ('environmentaldatatype', models.CharField(blank=True, max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'SRI_outdoorenvironmentald',
            },
        ),
        migrations.CreateModel(
            name='SRIControlLogic',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatacategorymeta')),
                ('controlsystem', models.CharField(blank=True, choices=[('hvac', 'HVAC'), ('lighting', 'Lighting'), ('fenestration', 'Fenestration'), ('plant', 'Plant'), ('other', 'Other')], max_length=1000, null=True)),
                ('controltype', models.CharField(blank=True, choices=[('logic', 'Logic'), ('setpoint', 'Setpoint'), ('schedule', 'Schedule'), ('other', 'Other')], max_length=1000, null=True)),
            ],
            options={
                'db_table': 'SRI_controllogic',
            },
        ),
        migrations.CreateModel(
            name='SRIEnergyData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatacategorymeta')),
                ('enduse', models.CharField(blank=True, choices=[('hvac  ', 'HVAC'), ('lighting', 'Lighting'), ('appliances', 'Appliances'), ('DHW', 'DHW'), ('Pump', 'Pumps'), ('ventilation', 'Ventilation'), ('other', 'Other')], max_length=1000, null=True)),
                ('energysource', models.CharField(blank=True, max_length=1000, null=True)),
                ('scale', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'SRI_energydata',
            },
        ),
        migrations.CreateModel(
            name='SRIOperationalData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sridb.sridatacategorymeta')),
                ('systemdata', models.CharField(blank=True, max_length=1000, null=True)),
                ('systemtype', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'SRI_operationaldata',
            },
        ),
        migrations.AddIndex(
            model_name='sridatacategorymeta',
            index=models.Index(fields=['objectclass'], name='SRI_datacat_objectc_8c8463_idx'),
        ),
    ]
